export default {
	extends: ["@commitlint/config-conventional"],
	rules: {
		"type-enum": [
			2,
			"always",
			[
				"feat",
				"fix",
				"perf",
				"refactor",
				"test",
				"docs",
				"build",
				"ci",
				"chore",
				"style",
				"revert",
			],
		],
		"scope-enum": [
			2,
			"always",
			[
				"core",
				"authority",
				"leaf",
				"oidc",
				"cli",
				"did",
				"explorer",
				"home",
				"learn",
				"ui",
				"release",
				"ci",
				"deps",
				"tests",
				"e2e",
				"scripts",
				"repo",
			],
		],
		"scope-empty": [2, "never"],
		"subject-case": [2, "never", ["upper-case", "pascal-case", "start-case"]],
		"subject-full-stop": [2, "never", "."],
		"header-max-length": [2, "always", 100],
		"body-max-line-length": [2, "always", 120],
	},
};
